name: dart_strapi
description: dart client for Strapi V4
version: 2.0.0
homepage: https://github.com/xantiagoma/dart_strapi

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  dio: ^4.0.4
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  tuple: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.7
  freezed: ^1.1.1
  json_serializable:
  test: ^1.17.12
