name: dart_strapi
description: http client for strapi, you can access your models by name or the custom ones using the http client.
version: 1.1.0
homepage: https://github.com/xantiagoma/dart_strapi

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0
  freezed_annotation: ^0.14.1

dev_dependencies:
  build_runner: ^1.12.2
  freezed: ^0.14.1+2
  json_serializable: ^4.1.0
